<a href="https://colab.research.google.com/github/LarryAP17/NumPy-Practise/blob/main/Numpy_Practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Numpy is more memory efficient and can work with multiple data types compared to lists in python.

In [ ]:
import numpy as np
a=np.zeros(3)
print(a)

[0. 0. 0.]


# 2. Writing numpy arrays

In [ ]:
alist=np.array([1,2,3,4,5])
print(alist)
type(alist[2])

[1 2 3 4 5]


numpy.int64

2D

In [ ]:
twod=np.array([[1,2,3,4],["sec",1,5,4]])
print(twod)
print(twod.shape)

[['1' '2' '3' '4']
 ['sec' '1' '5' '4']]
(2, 4)


3D

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(z.ndim)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
(2, 2, 3)


shape of numpy array

In [ ]:
z=np.zeros(10)
print(z)
z.shape

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(10,)

Check dimension

In [ ]:
print(z.ndim)

1


# 3. Other stuffs

Generate From 2 to 10 with 5 elements

In [ ]:
x=np.linspace(2,10,5)
print(x)

[ 2.  4.  6.  8. 10.]


**Convert list to numpy array**

In [ ]:
x=[[1,2,3],[4,5,6]]
xs=np.array(x)
print(xs)
print(type(x))
print(type(xs))

[[1 2 3]
 [4 5 6]]
<class 'list'>
<class 'numpy.ndarray'>


Numpy can also save multiple data types like lists

In [ ]:
arr=np.array([["name","age"],["ovi",22]])
print(arr)
print(arr[0,1])
print(type(arr[0,1]))
print(type(arr[1,1]))

[['name' 'age']
 ['ovi' '22']]
age
<class 'numpy.str_'>
<class 'numpy.str_'>


**Type vs dtype**
Type is to know whether it is normal list or numpy array.The type of a NumPy array is numpy.ndarray
dtype shows the data type

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr)
print(arr.dtype)    #integer 64 bit

arr2 = np.array(['apple', 'banana', 'cherry'])
print(arr2)
print(arr2.dtype)   #Unicode string

[1 2 3 4]
int64
['apple' 'banana' 'cherry']
<U6


Creating Arrays With a Defined Data Type.
For i, u, f, S and U we can define size as well.
for example i4 means 4 byte (32 bit) integer.
If conversion is not possible python will show value error

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S') #String Fixed
print(arr)
print(arr.dtype)

a=np.array([111,2222,333355,33334222], dtype='i4')
print(a)
print(a.dtype)

b=np.array([111,2222,333355,33334222], dtype='i8')
print(b)
print(b.dtype)

[b'1' b'2' b'3' b'4']
|S1
[     111     2222   333355 33334222]
int32
[     111     2222   333355 33334222]
int64


**Converting Data Type on Existing Arrays using astype()**

In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('int')    #i is for integer 32 bit. use int for integer 64 bit

print(arr.dtype)
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int64


**Slicing arrays.
We can also define the step, like this [start:end:step]**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
z=arr[1:5]
print(z)
print(arr[:3])  #before 3
print(arr[4:])  #after 4
print(arr[1:5:2]) #1st to 5th with 2 steps

[2 3 4 5]
[1 2 3]
[5 6 7]
[2 4]


In [ ]:
#2D array slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])
print(arr[1, ::2])

[2 3 4]
[ 6  8 10]


# 4. Playing with numpy

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,5,4],[9,8,7]])
print(a+b)

[[ 7  7  7]
 [13 13 13]]
[[-5 -3 -1]
 [-5 -3 -1]]


In [ ]:
x=np.array([[3,2,3],[4,8,7]])
