<a href="https://colab.research.google.com/github/LarryAP17/NumPy-Practise/blob/main/NumPy_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using Numpy to Create and edit arrays

Array generation

In [ ]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


NumPy is usually imported under the np alias.
alias: In Python alias are an alternate name for referring to the same thing.
Create an alias with the as keyword while importing. Now the NumPy package can be referred to as np instead of numpy.
Here is an 1D array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


Here is a 2D array

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim) #To know Dimension

[[1 2 3]
 [4 5 6]]
2


3D array

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[2,9,8],[4,2,5]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[2 9 8]
  [4 2 5]]]
3


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
